# Generated by Django 3.1.2 on 2020-11-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancetutorial',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
