# Generated by Django 3.0.8 on 2020-10-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='videos',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='video'),
        ),
    ]
