# Generated by Django 3.0.8 on 2020-10-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='videos',
        ),
    ]
